### ISSUE TITLE
Some dependencies are vunerable

### ISSUE THREAD

**Issue by viveksdf** [viveksdf/mean-crud#1]

**Comment by GDLynx** [comment]
For packages that have been updated to patch the vulnerabilities an "npm audit fix" should fix this, see: https://docs.npmjs.com/getting-started/running-a-security-audit 

For packages that are not going to be updated and perhaps to "risky" to have in the project - these should be removed and replaced .

**Comment by viveksdf** [comment]
Create a pull request.

**Comment by GDLynx** [comment]
Done, The output was 0 vulnerabilities. Although this should be taken with a grain of salt.
